let wordMap = {
    i: 2,
    fi: 1,
    afi: 2,
    afii: 1,
    afiil: 1,
    afiilu: 1,
    afhiilu: 1,
    afhiiklu: 1,
    afhiiklqu: 1,
    afhiiklqqu: 1,
    f: 1,
    af: 1,
    afil: 1,
    afilu: 1,
    afhilu: 1,
    afhiklu: 1,
    afhiklqu: 1,
    afhiklqqu: 1,
    a: 1,
    ai: 1,
    ail: 1,
    ailu: 1,
    ahilu: 1,
    ahiklu: 1,
    ahiklqu: 1,
    ahiklqqu: 1,
    il: 1,
    ilu: 1,
    hilu: 1,
    hiklu: 1,
    hiklqu: 1,
    hiklqqu: 1,
    l: 1,
    lu: 1,
    hlu: 1,
    hklu: 1,
    hklqu: 1,
    hklqqu: 1,
    u: 1,
    hu: 1,
    hku: 1,
    hkqu: 1,
    hkqqu: 1,
    h: 1,
    hk: 1,
    hkq: 1,
    hkqq: 1,
    k: 1,
    kq: 1,
    kqq: 1,
    q: 2,
    qq: 1
  }
  
  Object.keys(wordMap).forEach(function(item) {
      if (wordMap[item] > 1) {
          console.log(`${item}: ${wordMap[item]} `)
      }
  })